### PR TITLE
feat(data saving): implemented the new saving method

### PR DESCRIPTION
**Pull request by MichielLangen**

### CODE REVIEW

**Comment by MichielLangen** [comment]
Something went wrong with the commits, some of them are double.
The code is fine though.

**Comment by matblom** [comment]
I see a lot of code that is not conforming the PEP8 standard. Make sure you have a plugin installed that checks it or formats it.

**Comment by matblom** [comment]
I see a lot of good changes being added after my review. There are two comments pending still though. Give me a sign when everything regarding this feature has been resolved so I can merge it! :)

**Comment by MichielLangen** [comment]
Everything from issue #13, #14 and #34 is integrated and this pull request should be good to merge.

**Pull request merged**
